[package]
name = "rust-trie"
version = "0.1.0"
authors = ["Alex Garrett <agarrettR8@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.2.10"

[[bench]]
name = "bench_trie"
harness = false